[options]
db_host = localhost
db_port = 5432
db_user = adsodoo1
db_password = 123
db_name = odoo-erp-manufacture
default_productivity_apps = True
admin_passwd = $pbkdf2-sha512$600000$/X.PsbbWWmtNCQGgVOpd6w$56LnRz./F162A/zJCgr7d/Z343pBDfJSwiuOXbN3Tuyj5JPqav1U7Ga.v6SUD.3EHzBFyPFqi5.dzTZYuuyaEQ

; di debian/odoo.conf
workers = 0
max_cron_threads = 1
log_level = warn
proxy_mode = False
